### ISSUE TITLE
(No. 17 B) Export/Print Filters/Parameters [ Hard ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#98] opened 2019-01-22 23:55 UTC
from #93 \:
I suggest including “optimization parameters” as a potential export along with the results. If users print and export their results they may need to understand the parameters they used for each result.

**Comment by jtutak** [comment] 2019-02-01 22:33
Dupe of #106

**Closed by jtutak** 2019-02-01 22:33 UTC
